# Generated by Django 5.2.3 on 2025-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('type_of_project', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=200)),
                ('location_url', models.CharField(max_length=300)),
                ('number_of_units', models.CharField(max_length=100)),
                ('available_units', models.CharField(max_length=100)),
                ('available_facing', models.CharField(max_length=100)),
                ('available_sizes', models.CharField(max_length=100)),
                ('rera_approved', models.BooleanField(blank=True, null=True)),
                ('select_amenities', models.CharField(blank=True, max_length=255, null=True)),
                ('highlights', models.CharField(max_length=100)),
                ('type_of_approval', models.CharField(max_length=100)),
                ('total_project_area', models.CharField(max_length=100)),
                ('contact_info', models.IntegerField()),
                ('pricing', models.IntegerField()),
                ('imgae', models.ImageField(blank=True, null=True, upload_to='project_image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='project-video/')),
                ('document', models.FileField(blank=True, null=True, upload_to='project-doc/')),
            ],
        ),
    ]
