# Generated by Django 5.2.3 on 2025-11-26 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('MARKETER_EXPORT', 'Marketer Export'), ('MARKETER_EXPORT_PRO', 'Marketer Export Pro'), ('PROFESSIONAL_SINGLE', 'Professional Single'), ('COMPANY_NORMAL', 'Company Normal'), ('COMPANY_PRO', 'Company Pro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
