# Generated by Django 5.0.3 on 2025-11-23 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prop", "0002_addproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reel", models.FileField(blank=True, null=True, upload_to="reels/")),
                ("description", models.CharField(max_length=50)),
                ("likeCount", models.IntegerField(default=0)),
                ("Comments", models.CharField(blank=True, max_length=255, null=True)),
                ("commentCount", models.IntegerField(default=0)),
                ("shareCount", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
